version: '3.9'
services:

  minio: 
    hostname: minio
    container_name: minio
    image: 'minio/minio:RELEASE.2024-04-06T05-26-02Z'
    ports:
      - '${FORWARD_MINIO_PORT:-9000}:9000'
      - '${FORWARD_MINIO_CONSOLE_PORT:-9090}:9090'
    environment:
      MINIO_ROOT_USER: 'minio_access_key'
      MINIO_ROOT_PASSWORD: 'minio_secret_key'
    command: minio server /data/minio --console-address ":9090"
    networks:
      - oss_gharchivedata_orchestration_airflow_default

  minio-init-buckets:
    image: minio/mc:latest
    tty: true 
    depends_on:
      - minio
    entrypoint: > 
        /bin/sh -c "
        /usr/bin/mc alias set local http://minio:9000 minio_access_key minio_secret_key;
        /usr/bin/mc mb --ignore-existing local/gh-archive-data-raw;
        /usr/bin/mc mb --ignore-existing local/gh-archive-data-curated;
        /usr/bin/mc mb --ignore-existing local/gh-archive-data-analytics;
        " 
    networks:
      - oss_gharchivedata_orchestration_airflow_default

  postgres:
    image: postgres
    restart: unless-stopped
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_DB: 'metastore_db'
      POSTGRES_USER: 'hive'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    volumes:
      - hive-db:/var/lib/postgresql
    networks:
      - oss_gharchivedata_orchestration_airflow_default

  hive-metastore:
    image: apache/hive:4.0.0
    depends_on:
      - postgres
    restart: unless-stopped
    container_name: hive-metastore
    hostname: hive-metastore
    environment:
      DB_DRIVER: postgres
      SERVICE_NAME: 'metastore'
      SERVICE_OPTS: '-Xmx1G -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
                     -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore_db
                     -Djavax.jdo.option.ConnectionUserName=hive
                     -Djavax.jdo.option.ConnectionPassword=password'
    ports:
        - '9083:9083'
    volumes:
        - warehouse:/opt/hive/data/warehouse
        - type: bind
          source: jar/postgresql-42.5.6.jar
          target: /opt/hive/lib/postgres.jar
    networks:
      - oss_gharchivedata_orchestration_airflow_default
      
  hiveserver2:
    image: apache/hive:4.0.0
    depends_on:
      - hive-metastore
    restart: unless-stopped
    container_name: hiveserver2
    hostname: hiveserver2
    environment:
      HIVE_SERVER2_THRIFT_PORT: 10000
      SERVICE_OPTS: '-Xmx1G -Dhive.metastore.uris=thrift://hive-metastore:9083'
      IS_RESUME: 'true'
      SERVICE_NAME: 'hiveserver2'
    ports:
      - '10000:10000'
      - '10002:10002'
    volumes:
      - warehouse:/opt/hive/data/warehouse
    networks:
      - oss_gharchivedata_orchestration_airflow_default

  trino:
    hostname: trino 
    image: 'trinodb/trino:latest'
    ports:
      - '8080:8080'
    volumes:
      - ./etc/catalog:/etc/trino/catalog
    networks:
      - oss_gharchivedata_orchestration_airflow_default

  dremio:
    platform: linux/x86_64
    image: dremio/dremio-oss:latest
    ports:
      - 9047:9047
      - 31010:31010
      - 32010:32010
      - 45678:45678
    container_name: dremio
    hostname: dremio
    networks:
      - oss_gharchivedata_orchestration_airflow_default
    
  nessie:
    image: projectnessie/nessie
    container_name: nessie
    ports:
      - "19120:19120"
    networks:
      - oss_gharchivedata_orchestration_airflow_default

  apache-superset:
    image: apache/superset
    container_name: superset  
    environment:
      - SUPERSET_SECRET_KEY=gJsA0bqlMARC2X3VYMSsPUNM41Za2dkveN67+PVHashc3sUSrl+fSOZ4
    ports:
      - "8088:8088"
    networks:
      - oss_gharchivedata_orchestration_airflow_default

volumes:
  minio:
    driver: local
  hive-db:
  warehouse:

networks:
  oss_gharchivedata_orchestration_airflow_default:
    external: true
